version: "3.8"

services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - solr:/var/solr
    command:
      - solr-precreate
      - gettingstarted

# TODO create a collection via an init container that depends on solr?

volumes:
  solr:

