version: '3'
services:
  redis:
    image: redis:5.0.5-alpine
    volumes:
    - ./config/redis/redis.conf:/usr/local/etc/redis.conf
    ports:
       - "6379"

  db:
    restart: unless-stopped
    image: postgis/postgis:10-2.5-alpine
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready --username ${POSTGRES_USER} --dbname ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  web:
    image: "${IMAGE_NAME}"
    volumes:
    - ./config/dhis2_home/dhis.conf:/DHIS2_home/dhis.conf
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
    - "8080"
