version: '3'

services:
  e2e-test:
    stdin_open: true
    image: "${IMAGE_NAME}"
    environment:
      RP_UUID: ${RP_UUID}
    command: >
      sh -c "mkdir -p /tmp/analytics-db && curl -SL https://databases.dhis2.org/sierra-leone/2.39.0/dhis2-db-sierra-leone.sql.gz gzip -d /tmp/analytics-db && sudo -u postgres psql dhis < dhis2-db-sierra-leone.sql && 
             ./wait-for-it.sh web:8080 -t 0 -- mvn test --batch-mode --no-transfer-progress -Dinstance.url=http://web:8080/api -Dtest.cleanup=false -Dgroups='analytics-api' -Djunit.jupiter.execution.timeout.mode=disabled -Duser.admin.username=admin -Duser.admin.password=district -Drp.enable=true -Drp.launch=api_test_master -Drp.attributes=version:master"
